name: Docker Image CI

on: [push, pull_request]

jobs:
  build-x86_64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image and test (x86_64)
      run: docker build . --file .github/workflows/Dockerfile --tag ubuntu-bolt:$(date +%s)

  build-aarch64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Build Docker image and test (aarch64)
        run: docker buildx build . --file .github/workflows/Dockerfile.aarch64

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure
        run: cmake -B ${{github.workspace}}\build llvm -DLLVM_ENABLE_PROJECTS=bolt -DLLVM_TARGETS_TO_BUILD="X86;AArch64" -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_ASSERTIONS=ON
      - name: Build and test
        run: cmake --build ${{github.workspace}}\build --target llvm-bolt
